### PR TITLE
:sparkles: drivers / form / remove form with regexp

### PR DESCRIPTION
**Pull request by guillaumecrespel**
with this api : ` form(/form.*/).remove()`

### CODE REVIEW

**Comment by fabienjuif** [comment]
since only remove works with this notation, this is better to do something like this I think : `form.remove(/form.*/)`

Because with your notation we can think we can do : `form(/form.*/).add(/* */)` for example.

**Comment by guillaumecrespel** [comment]
I think later, this notation is possible on other getter, on possibly on setter.
But at this time I've just need this.
And with documentation, I think not that notation can be disruptive ?

**Comment by fabienjuif** [comment]
Ok, at least add exception on others actions / selectors:

`throw new Error('[<action|selector name>] not implemented with regexp form selector')`

**Comment by guillaumecrespel** [comment]
I don't find the way to implement this neatly 😥

**Comment by fabienjuif** [comment]
What about this for a first version : 
 - `form.find(/form.*/)` and the user can do what he wants

```js
const formsNames = form.find(/contact.*/)
forms.forEach(contactForm => form(contactForm).remove())
forms.forEach(contactForm => form(contactForm).set({ admin: true }))
// ...
```

And later it opens:
```js
form.remove(form.find(/contact.*/))
form.set({ admin: true })(form.find(/contact/*))
// ...
```

**Comment by guillaumecrespel** [comment]
Thx dude :)
I've implemented this on #196

**Pull request closed without merging**
